requires "PDL";
requires "PDL::Statistics";
requires "Statistics::Descriptive"
requires "Test::More"
requires "List::Util"
requires "Scalar::Util"
requires "List::MoreUtils"
requires "List::MoreUtils::XS"
requires "rlib"
